// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMInb_c03h2HkySsOCohOQMdTzKXOtmyU',
    appId: '1:1066444850166:web:504e8c3e2abc8ecf6c3dd7',
    messagingSenderId: '1066444850166',
    projectId: 'auto-vault-9517b',
    authDomain: 'auto-vault-9517b.firebaseapp.com',
    storageBucket: 'auto-vault-9517b.appspot.com',
    measurementId: 'G-CCYEVXQ41Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpm2MZNJUF2UZimKMrRFhxq-mSAzSzId4',
    appId: '1:1066444850166:android:9601f731b6a30dd56c3dd7',
    messagingSenderId: '1066444850166',
    projectId: 'auto-vault-9517b',
    storageBucket: 'auto-vault-9517b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkm4Gg-rKL4qQHEqGQnhSzDbbMTI_9FA4',
    appId: '1:1066444850166:ios:74b05c2437d8853a6c3dd7',
    messagingSenderId: '1066444850166',
    projectId: 'auto-vault-9517b',
    storageBucket: 'auto-vault-9517b.appspot.com',
    iosClientId: '1066444850166-12rt0i6tcp69ojh9tfe9jamd3h65nsic.apps.googleusercontent.com',
    iosBundleId: 'com.example.autoVault',
  );
}
